name: Build SimpleEconomy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simpleeconomy-jar
          path: build/libs/*.jar
